version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./smart_home/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - smarthome-network

  temperature-api:
    build: ./smart_home/services
    container_name: temperature-api
    ports:
      - "${TEMPERATURE_API_PORT}:${TEMPERATURE_API_PORT}"
    depends_on:
      - postgres
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_started
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TEMPERATURE_API_URL=${TEMPERATURE_API_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

volumes:
  postgres_data:

networks:
  smarthome-network:
    driver: bridge
